class Const:
    EXCHANGE_RATE = 'exchangeRate'
    SENDING_CURRENCY = 'sendingCurrency'
    SENDING_CURRENCY_ID = 'sendingCurrencyId'
    RECEIVING_CURRENCY = 'receivingCurrency'
    RECEIVING_AMOUNT = 'receivingAmount'
    RECEIVING_CURRENCY_ID = 'receivingCurrencyId'
    ACCEPTED_CURRENCY = 'accepted_currency'
    RECEIVING_COUNTRY_ID = 'receivingCountryId'
    NAME = 'name'
    ID = 'id'
    CODE = 'code'
    FEES = 'fees'
    AMOUNT = 'amount'
    CURRENCY = 'currency'
    DESTINATION = 'destination'
    ACCEPTED_AMOUNT = 'acceptedAmount'
    WITHDRAW_CURRENCY = 'withdrawCurrency'
